import {Contact} from '../../interface/contact.interface';
import {role} from '../enum/role.enum';

export const defaultContacts: Contact[] = [
  {
    id: 1,
    name: 'Juan',
    role: role.Cliente,
    number: 43123241,
    email: 'juan@gmail.com',
  },
  {
    id: 2,
    name: 'Maria',
    role: role.Empleado,
    number: 43123241,
    email: 'maria@gmail.com',
  },
  {
    id: 3,
    name: 'Pepita',
    role: role.Cliente,
    number: 43123241,
    email: 'pepita@gmail.com',
  },
  {
    id: 4,
    name: 'Mama',
    role: role.Cliente,
    number: 43123241,
    email: 'mama@gmail.com',
  },
  {
    id: 5,
    name: 'Jose',
    role: role.Empleado,
    number: 43123241,
    email: 'jose@gmail.com',
  },
  {
    id: 6,
    name: 'Daniel',
    role: role.Cliente,
    number: 43123241,
    email: 'daniel@gmail.com',
  },
  {
    id: 7,
    name: 'Jeronimo',
    role: role.Empleado,
    number: 43123241,
    email: 'jeronimo@gmail.com',
  },
  {
    id: 8,
    name: 'Tomas',
    role: role.Cliente,
    number: 43123241,
    email: 'tomas@gmail.com',
  },
  {
    id: 11,
    name: 'Jacobo',
    role: role.Cliente,
    number: 43123241,
    email: 'jacobo@gmail.com',
  },
  {
    id: 10,
    name: 'Angel',
    role: role.Cliente,
    number: 43123241,
    email: 'angel@gmail.com',
  },
  {
    id: 12,
    name: 'Gilberto',
    role: role.Empleado,
    number: 4312,
    email: 'gilberto@gmail.com',
  },
  {
    id: 13,
    name: 'Isaac',
    role: role.Cliente,
    number: 12331243,
    email: 'Isaac@gmail.com',
  },
  {
    id: 14,
    name: 'Cristiansss',
    role: role.Empleado,
    number: 314234,
    email: 'cristins@gmail.com',
  },
  {
    id: 15,
    name: 'Nicolas',
    role: role.Cliente,
    number: 123313,
    email: 'nicolas@gmail.com',
  },
  {
    id: 16,
    name: 'Alfonso',
    role: role.Empleado,
    number: 12343143,
    email: 'alfonso@gmail.com',
  },
];
